# Configure main menu and social menu

[[main]]
    identifier = "home"
    name = "Home"
    url = "/"

[[main]]
    identifier = "search"
    name = "Search"
    url = "/page/search/"

[[main]]
    identifier = "links"
    name = "Links"
    url = "/page/links/"

[[main]]
    identifier = "archives"
    name = "Archives"
    url = "/page/archives/"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/CaiJimmy/hugo-theme-stack"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    url        = "https://twitter.com"
