name = "my-blog-workers"
main = "src/index.ts"
compatibility_date = "2024-04-01"

kv_namespaces = [
  { binding = "BLOG_ARTICLES", id = "", preview_id = "" },
  { binding = "BLOG_USERS", id = "", preview_id = "" },
  { binding = "BLOG_SETTINGS", id = "", preview_id = "" }
]

vars = {
  JWT_SECRET = "your-secret-key",
  ADMIN_EMAIL = "admin@example.com"
}

route = "api.example.com/*"